import type { CrisisDashboardProps } from "./types";

// Sample crisis used when the inspector or a no-arg call needs a fallback.
// Mirrors the shape `generateCrisis()` would return for a moderate Santiago
// earthquake, but keeps deterministic values so the inspector renders the
// same content every time.

export const SAMPLE_CRISIS: CrisisDashboardProps = {
  crisis: {
    id: "crisis-sample",
    type: "earthquake",
    severity: "high",
    title: "Terremoto magnitud 7 en Santiago de Chile",
    description: "Terremoto magnitud 7 en Santiago de Chile",
    location: {
      lat: -33.4489,
      lng: -70.6693,
      name: "Santiago de Chile",
    },
    affectedRadius: 15.0,
    timestamp: "2026-05-09T12:00:00Z",
  },
  safeZones: [
    {
      id: "zone-1",
      name: "Hospital Central",
      type: "hospital",
      location: { lat: -33.4250, lng: -70.6650 },
      capacity: 400,
      status: "open",
      distance: 2.79,
      phone: "+56 2 2442 9141",
    },
    {
      id: "zone-2",
      name: "Hospital Regional Sur",
      type: "hospital",
      location: { lat: -33.4640, lng: -70.6840 },
      capacity: 600,
      status: "full",
      distance: 2.11,
      phone: "+56 2 2019 1781",
    },
    {
      id: "zone-3",
      name: "Albergue Estadio Municipal",
      type: "shelter",
      location: { lat: -33.4520, lng: -70.6580 },
      capacity: 1500,
      status: "open",
      distance: 1.55,
      phone: "+56 2 2334 1287",
    },
    {
      id: "zone-4",
      name: "Polideportivo Comunal",
      type: "shelter",
      location: { lat: -33.4380, lng: -70.6710 },
      capacity: 800,
      status: "open",
      distance: 1.21,
      phone: "+56 2 2778 4521",
    },
    {
      id: "zone-5",
      name: "Estación de Bomberos N°1",
      type: "fire_station",
      location: { lat: -33.4470, lng: -70.6720 },
      capacity: 50,
      status: "open",
      distance: 0.40,
      phone: "+56 2 2562 8030",
    },
    {
      id: "zone-6",
      name: "Comisaría Central",
      type: "police",
      location: { lat: -33.4500, lng: -70.6660 },
      capacity: 80,
      status: "open",
      distance: 0.42,
      phone: "+56 2 2922 1100",
    },
    {
      id: "zone-7",
      name: "Plaza de Armas",
      type: "assembly_point",
      location: { lat: -33.4378, lng: -70.6504 },
      capacity: 5000,
      status: "open",
      distance: 2.03,
    },
    {
      id: "zone-8",
      name: "Parque Central",
      type: "assembly_point",
      location: { lat: -33.4570, lng: -70.6790 },
      capacity: 2500,
      status: "open",
      distance: 1.42,
    },
  ],
  checklist: [
    {
      id: "chk-1",
      text: "Agacharse, cubrirse y sujetarse hasta que el sismo termine",
      checked: false,
      priority: "immediate",
      category: "seguridad",
    },
    {
      id: "chk-2",
      text: "Alejarse de ventanas, espejos y objetos que puedan caer",
      checked: false,
      priority: "immediate",
      category: "seguridad",
    },
    {
      id: "chk-3",
      text: "Evaluar lesiones propias y de personas cercanas",
      checked: false,
      priority: "immediate",
      category: "evaluación",
    },
    {
      id: "chk-4",
      text: "Revisar daños estructurales visibles antes de moverse",
      checked: false,
      priority: "immediate",
      category: "evaluación",
    },
    {
      id: "chk-5",
      text: "Salir del edificio por escaleras (NO usar ascensores)",
      checked: false,
      priority: "short-term",
      category: "evacuación",
    },
    {
      id: "chk-6",
      text: "Trasladarse a la zona segura más cercana",
      checked: false,
      priority: "short-term",
      category: "logística",
    },
    {
      id: "chk-7",
      text: "Inspección estructural profesional del inmueble",
      checked: false,
      priority: "long-term",
      category: "preparación",
    },
    {
      id: "chk-8",
      text: "Stock de agua y alimentos para 72 horas mínimo",
      checked: false,
      priority: "long-term",
      category: "logística",
    },
  ],
  resources: [
    {
      id: "res-1",
      name: "Agua potable",
      category: "water",
      have: 800,
      need: 5000,
      unit: "litros",
      critical: true,
    },
    {
      id: "res-2",
      name: "Alimentos no perecibles",
      category: "food",
      have: 950,
      need: 3000,
      unit: "raciones",
      critical: false,
    },
    {
      id: "res-3",
      name: "Botiquines",
      category: "medical",
      have: 22,
      need: 50,
      unit: "unidades",
      critical: false,
    },
    {
      id: "res-4",
      name: "Carpas / refugios",
      category: "shelter",
      have: 8,
      need: 50,
      unit: "unidades",
      critical: true,
    },
    {
      id: "res-5",
      name: "Radios portátiles",
      category: "communication",
      have: 28,
      need: 50,
      unit: "unidades",
      critical: false,
    },
  ],
  alerts: [
    {
      id: "alert-1",
      service: "electricity",
      status: "outage",
      message: "Cortes de energía en sectores afectados",
      updatedAt: "2026-05-09T12:05:00Z",
    },
    {
      id: "alert-2",
      service: "water",
      status: "degraded",
      message: "Suministro de agua potable comprometido",
      updatedAt: "2026-05-09T12:05:00Z",
    },
    {
      id: "alert-3",
      service: "gas",
      status: "outage",
      message: "Gas cortado preventivamente",
      updatedAt: "2026-05-09T12:05:00Z",
    },
    {
      id: "alert-4",
      service: "communications",
      status: "degraded",
      message: "Saturación de red móvil — usar SMS",
      updatedAt: "2026-05-09T12:05:00Z",
    },
    {
      id: "alert-5",
      service: "transport",
      status: "outage",
      message: "Metro y trenes detenidos para inspección",
      updatedAt: "2026-05-09T12:05:00Z",
    },
  ],
  timeline: [
    {
      id: "tl-1",
      phase: "first_5_min",
      action: "Resguardarse hasta que cese el sismo",
      completed: false,
      order: 0,
    },
    {
      id: "tl-2",
      phase: "first_hour",
      action: "Activar puntos de encuentro",
      completed: false,
      order: 1,
    },
    {
      id: "tl-3",
      phase: "first_day",
      action: "Distribución inicial de agua y alimentos",
      completed: false,
      order: 2,
    },
    {
      id: "tl-4",
      phase: "first_week",
      action: "Restablecimiento progresivo de servicios",
      completed: false,
      order: 3,
    },
  ],
  weather: {
    temperature: 16.5,
    windSpeed: 8.2,
    humidity: 57,
    description: "Despejado",
    alerts: [],
  },
  header: {
    title: "Terremoto · Santiago de Chile",
    subtitle:
      "Severidad alta · radio 15 km · 8 zonas seguras · 4 acciones inmediatas",
  },
};
